### PR TITLE
Update vim-vimparser (support BLOB, CONST, EVAL, HEREDOC, METHOD)

### LINKED ISSUE #337: Vint erroneously marks default values for function arguments as errors
### The Problem
The following function is valid vimscript. Vint, however, marks the equals sign an "unexpected token."
```vimscript
function! TestFunction(test = 1) abort
    echo a:test
endfunction
```
```
$ vint test.vim
test.vim:1:29: unexpected token: = (see vim-jp/vim-vimlparser)
Total violations: 1
```

### Reproduce
1. Create a file called test.vim
2. Add the following lines to the file:
```vimscript
function! TestFunction(test = 1) abort
    echo a:test
endfunction
```
3. Optionally, source the file and run `:call TestFunction()` and `:call TestFunction(267)` to see that the function works.
4. Exit vim
5. Run `vint test.vim` on your command line and see vint return an error incorrectly.

I took a quick look but I didn't see that this had been reported before.

### LINKED ISSUE #357: Method calls reported as errors
Vint version: 0.4a4.dev5+gfb6fa16

In the following snippet, Vint shows an error: `E488: Trailing characters: - (see vim-jp/vim-vimlparser)`

```vim
let s = "   a"->trim()
```

However this code is valid, see `:h method` for details (or run it interactively and print the value of `s`).

### PR DESCRIPTION
**Pull request by tyru**
Fix #357
Fix #337

---

Update to vim-jp/vim-vimlparser@90895c3 .
And just I have added node types for new nodes.

---

But this PR doesn't solve `map()`'s arity errors.
This should be fixed by separated PR, I think.

スクリーンショット 2020-03-06 23 40 21

### CODE REVIEW

**Comment by tyru** [comment]
ah, BLOB and CONST are included to the previous vimlparser.py, but node types are not supported?

**Comment by tyru** [comment]
> `map()`'s arity errors.

was caused by
https://github.com/Vimjas/vint/blob/fb6fa167a488d6e5b63d3516ca9c24eba0fc35b7/vint/linting/policy/prohibit_invalid_map_call.py

The policy should care NODE_METHOD.

**Comment by tyru** [comment]
Zapped all issues, and added issue numbers to top comment.

**Comment by tyru** [comment]
@blueyed Can I merge this?

**Comment by tyru** [comment]
It looks like I cannot merge this :o
Maybe collaborator cannot merge to master?

スクリーンショット 2020-03-19 19 46 38

**Comment by blueyed** [comment]
@tyru updated your perms - it was "Triage" before only, now it is "Write".

**Comment by tyru** [comment]
@blueyed Thanks!

**Comment by Shane-XB-Qian** [comment]
hello~ did this included https://github.com/vim-jp/vim-vimlparser/pull/159 ?
looks that fixed earlier than those, but 'default argument =' looks still not supported..
i install vint by pip, or was there a way to upd vimlparser manually?

**Comment by Shane-XB-Qian** [comment]
i just tried to verify the effective result.. so far looks a bit not-upd-2-date.. 
and a bit slow (with syntastic) if viml more than thousand lines.. fyi...........

**Pull request merged**
